# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data]
highlighter:      pygments

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            Miguel Machado
tagline:          'Ce Student'
description:      ''
url:              kabombom.github.io
baseurl:          '/'
paginate:         3
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Author Info
author:
  name:           'Miguel Machado'
  url:            kabombom.github.io

# Social Integration
social:
  twitter:        
  disqus:         
  addthis_pubid:  

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:      
  super_proxy_url:  

# Github
github:
  repo:           kabombom.github.io
  feedback:       

# Version Info
version:          1.0.0
